
<button class="scalable" type="button" id="<?= /* @noEscape */ $block->getHtmlId() ?>" data-mage-init='{"freshMailTestConnection":{
    "url": "<?= $block->escapeUrl($block->getAjaxUrl()) ?>",
    "elementId": "<?= /* @noEscape */ $block->getHtmlId() ?>",
    "successText": "<?= $block->escapeHtmlAttr(__('Successful!')) ?>",
    "failedText": "<?= $block->escapeHtmlAttr(__('Connection failed!')) ?>",
    "fieldMapping": "<?= /* @noEscape */ $block->getFieldMapping() ?>"}, "validation": {}}'>
    <span id="<?= /* @noEscape */ $block->getHtmlId() ?>_result"><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
</button>
